<a href="https://colab.research.google.com/github/Analyticdave/Data_Analytics_with_Python/blob/main/Numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing numpy

import numpy as np





In [ ]:
# Creating arrays

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
arr1 =  np.array([6,7,8,9,10])
print(arr1)

[ 6  7  8  9 10]


In [ ]:
# checking array type
print(arr1)
print(type(arr1))

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
# creating arrays with Tupple
tupple_arr = np.array((11,12,13,14,15))
print(tupple_arr)

[11 12 13 14 15]


In [ ]:
# Creating 2D arrays
arr2 = np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(arr2)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [ ]:
# Creating 3D arrays
arr3 = np.array([[[1,3,5,7,9],[2,4,6,8,10],[1,2,3,4,5]]])
print(arr3)


[[[ 1  3  5  7  9]
  [ 2  4  6  8 10]
  [ 1  2  3  4  5]]]


In [ ]:
# Checking the ndim of an arry
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
1
2
3


In [ ]:
# creating arrays with higher dimensions

arr_higher = np.array([10, 20, 30, 40], ndmin=7)

print(arr_higher)
print('number of dimensions :', arr_higher.ndim)

[[[[[[[10 20 30 40]]]]]]]
number of dimensions : 7


In [ ]:
# ACCESSING ARRAYS

# 1-D Arrays

arr = np.array([100, 200, 300, 400])

print(arr[0])
print(arr[2] )
print(arr[2] + arr[3])

100
300
700


In [ ]:
# Accessing 2-D Arrays

arr = arr2
print(arr2)
print(arr[0,1])
print(arr[1,4])

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
3
10


In [ ]:
#Accessing 3-D Arrays
arr = arr3
print(arr3)
print(arr[0,1,2])

[[[ 1  3  5  7  9]
  [ 2  4  6  8 10]
  [ 1  2  3  4  5]]]
6


In [ ]:
# Negative Indexing
print(arr2)
print(arr2[1,-2])

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
8


In [ ]:
# Slicing  Arrays [start:stop:step]
# 1-D Array

arr4 = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr4)

print(arr4[0:4])

print(arr4[1:9:2])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4]
[2 4 6 8]


In [ ]:
print(arr4[::2])
print(arr4[::1])

[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Slicing in 2-D Arrays
arr5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr5[1, 1:4])
print(arr5[0:2, 2])
print(arr5[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
# Copy and View of Arrays
arr_copy = arr5.copy()
arr_view = arr5.view()
print('copy:', arr_copy.base)
print('view', arr_view.base)

copy: None
view [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Iteration with arrys(This is just like using a for loop. Iterating means going through elements one by one.)
# For 1-D Array
arr = np.array([1, 2, 3])

for x in arr:
    print(x)


1
2
3


In [ ]:
# for n-D Array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
# for 2-D Array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [ ]:
# For 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating throup an Array using nditer()


arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Iterating Array With Different Data Types using flags = buffer amd OP-DTYPES = S


arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [ ]:
# Iterating With Different Step Size

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# This line skips one element bescause the step is 2
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [ ]:
# Enumerated Iteration Using ndenumerate()


arr = np.array([5, 2, 23])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 5
(1,) 2
(2,) 23


In [ ]:
# Enumerate on following 2D array's elements:

arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40
(1, 0) 50
(1, 1) 60
(1, 2) 70
(1, 3) 80


In [ ]:
# Joinning of Arrays using Concatenate()

arr1 = np.array([1, 5, 2])

arr2 = np.array([4, 3, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 5 2 4 3 6]


In [ ]:
# Joining two 2-D Arrays 'Note that the axis must be soecified. 0 is x while 1 is y-axis'

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Joining Arrays Using Stack Functions dstack(), hStack() and vstack()

# Stacking along column with hstack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)



[1 2 3 4 5 6]


In [ ]:
# Stacking along rows with vstack

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking Along the Height

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# Spliting Numpy Arrays using array_split()

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(arr, 2)

print(new_arr)

[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
# Accessing Splited Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(arr, 2)

print(new_arr)

print(new_arr[0])
print(new_arr[1])


[array([1, 2, 3]), array([4, 5, 6])]
[1 2 3]
[4 5 6]


In [ ]:
# Spliting 2-D Arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print('The main array:', arr)

new_arr = np.array_split(arr, 2)

print('Splitte array:',new_arr)

The main array: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Splitte array: [array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [ ]:
# Splittind Arrays along columns and rows with vsplit() and hsplit()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr = np.hsplit(arr, 3)

print(new_arr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# for arrays using the where clause

arr = np.array([1, 2, 6,3, 4, 5, 6, 4])

x = np.where(arr == 6)

print(x)

(array([2, 6], dtype=int64),)


In [ ]:
# searching for even number position
arr = np.array([1, 2, 3, 4, 5, 6, 7])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5], dtype=int64),)


In [ ]:
# Searching for odd numbers position
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4], dtype=int64),)


In [ ]:
# Search and sort using searchsorted()

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
# starting the sort from left

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side = 'right')

print(x)

2


In [ ]:
# sorting to the right
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side = 'left')

print(x)

1


In [ ]:
# Sorting of Arrays using sort()

arr = np.array(['pineaple', 'banana', 'Lemon', 'Apple','Grape'])

print(np.sort(arr))

['Apple' 'Grape' 'Lemon' 'banana' 'pineaple']


In [ ]:
#Sorting 2-D Arrays

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
# creating a filter for arrays: A filter uses boolean decision to decide the elements in a new array
# It returns true is the element meets a prescribed condition and false if it does not.

arr = np.array([2, 15, 6, 1])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[2 6]


In [ ]:
arr = np.array([2, 15, 6,1 ])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
# if the element is higher than 2, set the value to True, otherwise False:
    if element > 2:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, True, False]
[15  6]


In [ ]:
# creating a filter Array that only print Even numbers

arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
# if the element is completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
            filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [ ]:
# Creating a Filter for odd numbers
arr = np.array([1, 2, 3, 4, 5, 6, 7,9,10])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
# if the element is not completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 1:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[True, False, True, False, True, False, True, True, False]
[1 3 5 7 9]


In [ ]:
# Creating Filters directly From Arrays

arr = np.array([2, 5, 6, 1])

filter_arr = arr > 2

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True  True False]
[5 6]


In [ ]:
# Creating even numbers Filters from arrays directly

arr = np.array([1, 2, 3, 4, 5, 6, 7,9,10])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False False  True]
[ 2  4  6 10]


In [ ]:
# Creating Odd numbers filter directly from Arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

filter_arr = arr % 2 == 1

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)